Repository markedjs/marked, pull requests merged in 2018-12, with the labels that each got.

#1382 Update docs to include "Since" version
  docs/USING_ADVANCED.md
Labels: category: docs

#1385 Fix bold around autolink email address
  lib/marked.js
  test/specs/marked/marked.json
Labels: category: inline elements, category: links, category: mixed content

#1384 Make autolinks case insensitive
  lib/marked.js
  test/specs/marked/marked.json
Labels: category: links

#1387 [commonmark] make code fences compliant (+ fix 1058)
  lib/marked.js
  test/new/gfm_code.html
  test/new/gfm_code.md
  test/specs/commonmark/commonmark-spec.js
Labels: category: code blocks

#1400 Fix strong tag
  lib/marked.js
  test/specs/commonmark/commonmark-spec.js
Labels: category: inline elements

#1401 Fix duplicate heading id
  lib/marked.js
  test/new/cm_blockquotes.html
  test/new/cm_blockquotes.md
  test/new/toplevel_paragraphs.html
  test/new/toplevel_paragraphs.md
  test/original/markdown_documentation_basics.html
  test/unit/marked-spec.js
Labels: category: headings
