Repository markedjs/marked, pull requests merged in 2018-09, with the labels that each got.

#1335 Fix typographic substitution in (pre|code|kbd|script) blocks when smartypants=true
  lib/marked.js
  test/new/smartypants_code.html
  test/new/smartypants_code.md
Labels: category: code blocks, category: mixed content

#1338 Fix auto-linking email
  lib/marked.js
  test/specs/marked/marked-spec.js
  test/specs/marked/marked.json
Labels: category: links

#1337 fix inline code regex
  lib/marked.js
  test/specs/commonmark/commonmark-spec.js
  test/specs/marked/marked.json
Labels: category: code blocks
