Repository markedjs/marked, pull requests merged in 2018-02, with the labels that each got.

#1020 [linting] Use eslint to lint code. + minor refactoring + Travis CI setup
  .eslintrc.json
  .travis.yml
  lib/marked.js
  marked.min.js
  package-lock.json
  package.json
  test/browser/index.js
  test/browser/test.js
  test/index.js
Labels: RR - refactor & re-engineer

#1087 Switched out tabs for spaces
  test/index.js
Labels: L1 - broken

#1083 security: fix REDOS vulnerabilities
  lib/marked.js
  test/index.js
  test/new/headings_id.html
  test/new/headings_id.md
  test/new/redos_html_closing.html
  test/new/redos_html_closing.md
  test/new/redos_nolink.html
  test/new/redos_nolink.md
Labels: L0 - security

#1081 Update docs
  AUTHORS.md
  CONTRIBUTING.md
  LICENSE
  LICENSE.md
  README.md
  RELEASE.md
  USAGE_ADVANCED.md
  USAGE_EXTENSIBILITY.md
Labels: RR - refactor & re-engineer

#1076 Release 0.3.17 (template updates) - ??
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE/release.md
  AUTHORS.md
  marked.min.js
  package-lock.json
  package.json
Labels: RR - refactor & re-engineer

#1091 fix broken link
  CONTRIBUTING.md
Labels: RR - refactor & re-engineer

#1100 Update release template
  .github/PULL_REQUEST_TEMPLATE/release.md
Labels: proposal
