Repository markedjs/marked, pull requests merged in 2018-04, with the labels that each got.

#1196 Demo link outputtype
  docs/demo/demo.js
  docs/demo/index.html
Labels: category: docs

#1182 allow string arg from command line
  bin/marked
  docs/README.md
  test/unit/marked-spec.js
Labels: category: cli

#696 Added missing input flag
  man/marked.1
Labels: category: cli

#1160 CommonMark Tests
  package-lock.json
  package.json
  test/integration/commonmark.json
  test/integration/marked-spec.js
Labels: parser: CommonMark

#1207 Update readme with emoji
  README.md
Labels: category: docs

#1221 Add badges to README
  README.md
Labels: category: docs
