Repository markedjs/marked, pull requests merged in 2019-05, with the labels that each got.

#1464 Nested blockquotes
  lib/marked.js
  test/redos/nested_blockquote.js
  test/specs/redos-spec.js
Labels: L0 - security, category: blockquotes

#1432 add docs for workers
  docs/USING_ADVANCED.md
  docs/index.html
Labels: category: docs

#1451 Fix `<em>` issue with mixed content #1410
  lib/marked.js
  test/specs/commonmark/commonmark.0.29.json
  test/specs/new/em_list_links.html
  test/specs/new/em_list_links.md
Labels: category: inline elements, category: mixed content

#1492 Add security policy
  SECURITY.md
Labels: category: docs

#1491 Update supported spec versions
  docs/README.md
Labels: category: docs
