Repository markedjs/marked, pull requests merged in 2019-04, with the labels that each got.

#1457 use latest commit for demo master
  docs/demo/demo.js
Labels: category: docs

#1470 Gfm 0.29
  package-lock.json
  package.json
  test/specs/gfm/getSpecs.js
  test/specs/gfm/gfm.0.29.json
  test/specs/run-spec.js
Labels: category: tests

#1475 fix: failed commonmark examples 57 and 40
  lib/marked.js
  package-lock.json
  package.json
  test/specs/commonmark/commonmark.0.29.json
Labels: category: headings
