Repository markedjs/marked, pull requests merged in 2020-07, with the labels that each got.

#1720 clarify level of support for Markdown flavors
  docs/README.md
Labels: category: docs

#1729 Fix quick ref
  docs/demo/quickref.md
Labels: category: docs

#1730 update dev deps
  lib/marked.js
  marked.min.js
  package-lock.json
  package.json
Labels: dependencies

#1728 NFE: add dry run capabilities to default slugger
  docs/USING_PRO.md
  src/Slugger.js
  test/unit/marked-spec.js
Labels: category: headings

#1736 Regenerate lock file
  package-lock.json
Labels: dependencies
