Repository markedjs/marked, pull requests merged in 2020-05, with the labels that each got.

#1662 add tokenizer to option docs
  docs/USING_ADVANCED.md
Labels: category: docs

#1670 render code with and without language with the trailing newline
  src/Renderer.js
  test/specs/new/code_compensation_indent.html
  test/specs/new/code_consistent_newline.html
  test/specs/new/code_consistent_newline.md
Labels: category: code blocks

#1674 fix loose task list with no tokens
  src/Parser.js
  test/specs/new/list_loose_tasks.html
  test/specs/new/list_loose_tasks.md
Labels: category: lists

#1683 fix image links with escaped brackets
  src/Tokenizer.js
  src/rules.js
  test/specs/new/image_links.html
  test/specs/new/image_links.md
Labels: category: images

#1685 fix async highlight not async
  src/marked.js
  test/unit/marked-spec.js
Labels: category: code blocks
